# render.yaml
services:
  # 1. Веб-сервис
  - type: web
    name: messenger-transcribe-bot
    env: python
    plan: starter
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    # --- ИЗМЕНЕНИЕ ЗДЕСЬ: Новая команда запуска ---
    startCommand: "gunicorn --worker-class uvicorn.workers.UvicornWorker app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromGroup: variables_bot
      - key: REDIS_URL
        fromService:
          type: redis
          name: bot-redis
          property: connectionString

  # 2. Воркер Celery (остается без изменений)
  - type: worker
    name: celery-worker
    env: python
    plan: starter
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "celery -A celery_worker.celery_app worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromGroup: variables_bot
      - key: REDIS_URL
        fromService:
          type: redis
          name: bot-redis
          property: connectionString

  # 3. Redis (остается без изменений)
  - type: redis
    name: bot-redis
    plan: free
    ipAllowList: []