# config/transcrib_suggestion_config.py

# Список популярных языков для кнопок с быстрым выбором
DEFAULT_POPULAR_TRANSCRIPTION_LANGS = [
    {'code': 'km', 'title': 'Khmer', 'flag': '🇰🇭'},
    {'code': 'en', 'title': 'English', 'flag': '🇬🇧'},
    {'code': 'ru', 'title': 'Russian', 'flag': '🇷🇺'},
    {'code': 'de', 'title': 'German', 'flag': '🇩🇪'},
    {'code': 'de', 'title': 'Swiss German', 'flag': '🇨🇭'}, # Использует код 'de'
    {'code': 'ga', 'title': 'Irish', 'flag': '🇮🇪'},
    {'code': 'es', 'title': 'Spanish', 'flag': '🇪🇸'},
    {'code': 'fr', 'title': 'French', 'flag': '🇫🇷'},
]

DEFAULT_POPULAR_TRANSLATION_LANGS = [
    {'code': 'km', 'title': 'Khmer', 'flag': '🇰🇭'},
    {'code': 'en', 'title': 'English', 'flag': '🇬🇧'},
    {'code': 'ru', 'title': 'Russian', 'flag': '🇷🇺'},
    {'code': 'de', 'title': 'German', 'flag': '🇩🇪'},
    {'code': 'de', 'title': 'Swiss German', 'flag': '🇨🇭'}, # Использует код 'de'
    {'code': 'ga', 'title': 'Irish', 'flag': '🇮🇪'},
    {'code': 'es', 'title': 'Spanish', 'flag': '🇪🇸'},
    {'code': 'fr', 'title': 'French', 'flag': '🇫🇷'},
]

# Полная карта поддерживаемых языков для текстового ввода
SUPPORTED_LANGUAGES_MAP = {
    'khmer': 'km', 'km': 'km',
    'afrikaans': 'af', 'af': 'af',
    'arabic': 'ar', 'ar': 'ar',
    'armenian': 'hy', 'hy': 'hy',
    'azerbaijani': 'az', 'az': 'az',
    'belarusian': 'be', 'be': 'be',
    'bosnian': 'bs', 'bs': 'bs',
    'bulgarian': 'bg', 'bg': 'bg',
    'catalan': 'ca', 'ca': 'ca',
    'chinese': 'zh', 'zh': 'zh',
    'croatian': 'hr', 'hr': 'hr',
    'czech': 'cs', 'cs': 'cs',
    'danish': 'da', 'da': 'da',
    'dutch': 'nl', 'nl': 'nl',
    'english': 'en', 'en': 'en',
    'estonian': 'et', 'et': 'et',
    'finnish': 'fi', 'fi': 'fi',
    'french': 'fr', 'fr': 'fr',
    'galician': 'gl', 'gl': 'gl',
    'german': 'de', 'de': 'de',
    'swiss german': 'de',
    'greek': 'el', 'el': 'el',
    'hebrew': 'he', 'iw': 'he',
    'hindi': 'hi', 'hi': 'hi',
    'hungarian': 'hu', 'hu': 'hu',
    'icelandic': 'is', 'is': 'is',
    'indonesian': 'id', 'id': 'id',
    'irish': 'ga', 'ga': 'ga',
    'italian': 'it', 'it': 'it',
    'japanese': 'ja', 'ja': 'ja',
    'kannada': 'kn', 'kn': 'kn',
    'kazakh': 'kk', 'kk': 'kk',
    'korean': 'ko', 'ko': 'ko',
    'latvian': 'lv', 'lv': 'lv',
    'lithuanian': 'lt', 'lt': 'lt',
    'macedonian': 'mk', 'mk': 'mk',
    'malay': 'ms', 'ms': 'ms',
    'marathi': 'mr', 'mr': 'mr',
    'maori': 'mi', 'mi': 'mi',
    'nepali': 'ne', 'ne': 'ne',
    'norwegian': 'no', 'no': 'no',
    'persian': 'fa', 'fa': 'fa',
    'polish': 'pl', 'pl': 'pl',
    'portuguese': 'pt', 'pt': 'pt',
    'romanian': 'ro', 'ro': 'ro',
    'russian': 'ru', 'ru': 'ru',
    'serbian': 'sr', 'sr': 'sr',
    'slovak': 'sk', 'sk': 'sk',
    'slovenian': 'sl', 'sl': 'sl',
    'spanish': 'es', 'es': 'es',
    'swahili': 'sw', 'sw': 'sw',
    'swedish': 'sv', 'sv': 'sv',
    'tagalog': 'tl', 'tl': 'tl',
    'tamil': 'ta', 'ta': 'ta',
    'thai': 'th', 'th': 'th',
    'turkish': 'tr', 'tr': 'tr',
    'ukrainian': 'uk', 'uk': 'uk',
    'urdu': 'ur', 'ur': 'ur',
    'vietnamese': 'vi', 'vi': 'vi',
    'welsh': 'cy', 'cy': 'cy'
}